name: Qodana
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --loglevel=error --no-update-notifier --no-audit --no-fund

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0
        with:
          bootstrap: npm install
          args: --baseline,qodana.sarif.json

      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
